// dados.js
const locations = [
    
  {
    "id": 5,
    "nome": "Alexx Amatuzzi",
    "cidade": "Valinhos",
    "estado": "SP",
    "latitude": -22.9772,
    "longitude": -46.989,
    "cep": "13322020",
    "pais": "Brasil",
    "localizacao": "Valinhos, SP, Brasil",
    "descricao": "Usuário da cidade de Valinhos.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.9772,-46.989",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 6,
    "nome": "Ricardo Augusto Costa Raven",
    "cidade": "Hortolândia",
    "estado": "SP",
    "latitude": -22.8862883,
    "longitude": -47.2013605,
    "cep": "13186635",
    "pais": "Brasil",
    "localizacao": "Hortolândia, SP, Brasil",
    "descricao": "Usuário da cidade de Hortolândia.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.8862883,-47.2013605",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 7,
    "nome": "Carlos Eduardo Pereira de Souza",
    "cidade": "Campinas",
    "estado": "SP",
    "latitude": -22.9826214,
    "longitude": -47.1202832,
    "cep": "13054421",
    "pais": "Brasil",
    "localizacao": "Campinas, SP, Brasil",
    "descricao": "Usuário da cidade de Campinas.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.9826214,-47.1202832",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 8,
    "nome": "Adrian Roberto Chiminazzo",
    "cidade": "Valinhos",
    "estado": "SP",
    "latitude": -22.9813643,
    "longitude": -46.9938373,
    "cep": "13276409",
    "pais": "Brasil",
    "localizacao": "Valinhos, SP, Brasil",
    "descricao": "Usuário da cidade de Valinhos.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.9813643,-46.9938373",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 9,
    "nome": "Roberta Dos Santos Silva",
    "cidade": "Campinas",
    "estado": "SP",
    "latitude": -22.9710829,
    "longitude": -47.1572759,
    "cep": "13056204",
    "pais": "Brasil",
    "localizacao": "Campinas, SP, Brasil",
    "descricao": "Usuário da cidade de Campinas.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.9710829,-47.1572759",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 10,
    "nome": "Ingryd Micheli Breg",
    "cidade": "Limeira",
    "estado": "SP",
    "latitude": -22.5571965,
    "longitude": -47.3772316,
    "cep": "13486333",
    "pais": "Brasil",
    "localizacao": "Limeira, SP, Brasil",
    "descricao": "Usuário da cidade de Limeira.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.5571965,-47.3772316",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 11,
    "nome": "Josenil Roberto Braggion",
    "cidade": "Indaiatuba",
    "estado": "SP",
    "latitude": -23.1286709,
    "longitude": -47.2424757,
    "cep": "13348220",
    "pais": "Brasil",
    "localizacao": "Indaiatuba, SP, Brasil",
    "descricao": "Usuário da cidade de Indaiatuba.",
    "link": "https://www.google.com/maps/search/?api=1&query=-23.1286709,-47.2424757",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 12,
    "nome": "Everton F. de Andrade",
    "cidade": "Paulínia",
    "estado": "SP",
    "latitude": -22.7881625,
    "longitude": -47.1927215,
    "cep": "13142126",
    "pais": "Brasil",
    "localizacao": "Paulínia, SP, Brasil",
    "descricao": "Usuário da cidade de Paulínia.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.7881625,-47.1927215",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 13,
    "nome": "Thiago Gomes de Sousa",
    "cidade": "Campinas",
    "estado": "SP",
    "latitude": -22.9329629,
    "longitude": -47.0909205,
    "cep": "13050055",
    "pais": "Brasil",
    "localizacao": "Campinas, SP, Brasil",
    "descricao": "Usuário da cidade de Campinas.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.9329629,-47.0909205",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 14,
    "nome": "Carlos S Campos",
    "cidade": "Campinas",
    "estado": "SP",
    "latitude": -22.9262061,
    "longitude": -47.1001863,
    "cep": "13060022",
    "pais": "Brasil",
    "localizacao": "Campinas, SP, Brasil",
    "descricao": "Usuário da cidade de Campinas.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.9262061,-47.1001863",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 15,
    "nome": "Joseleyne de Souza Ribeiro",
    "cidade": "Campinas",
    "estado": "SP",
    "latitude": -22.9430521,
    "longitude": -47.0911774,
    "cep": "13050061",
    "pais": "Brasil",
    "localizacao": "Campinas, SP, Brasil",
    "descricao": "Usuário da cidade de Campinas.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.9430521,-47.0911774",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 16,
    "nome": "THAIS DUARTE ESNARRIAGA",
    "cidade": "Valinhos",
    "estado": "SP",
    "latitude": -22.9552089,
    "longitude": -46.9939365,
    "cep": "13272071",
    "pais": "Brasil",
    "localizacao": "Valinhos, SP, Brasil",
    "descricao": "Usuário da cidade de Valinhos.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.9552089,-46.9939365",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 17,
    "nome": "Heloísa Mendes",
    "cidade": "Hortolândia",
    "estado": "SP",
    "latitude": -22.8601,
    "longitude": -47.2127,
    "cep": "13181655",
    "pais": "Brasil",
    "localizacao": "Hortolândia, SP, Brasil",
    "descricao": "Usuário da cidade de Hortolândia.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.8601,-47.2127",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 18,
    "nome": "ALEXANDRE DA S. MENDES  BARROS",
    "cidade": "Campinas",
    "estado": "SP",
    "latitude": -22.9079159,
    "longitude": -47.0476421,
    "cep": "13026050",
    "pais": "Brasil",
    "localizacao": "Campinas, SP, Brasil",
    "descricao": "Usuário da cidade de Campinas.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.9079159,-47.0476421",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 19,
    "nome": "Mayara",
    "cidade": "Sumaré",
    "estado": "SP",
    "latitude": -22.8235953,
    "longitude": -47.2390337,
    "cep": "13175662",
    "pais": "Brasil",
    "localizacao": "Sumaré, SP, Brasil",
    "descricao": "Usuário da cidade de Sumaré.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.8235953,-47.2390337",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 20,
    "nome": "Rafael Silva Piranga",
    "cidade": "Valinhos",
    "estado": "SP",
    "latitude": -22.9772,
    "longitude": -46.989,
    "cep": "13331600",
    "pais": "Brasil",
    "localizacao": "Valinhos, SP, Brasil",
    "descricao": "Usuário da cidade de Valinhos.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.9772,-46.989",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 21,
    "nome": "esmael  Carvalho de souza",
    "cidade": "Valinhos",
    "estado": "SP",
    "latitude": -22.9841935,
    "longitude": -46.9805303,
    "cep": "13275616",
    "pais": "Brasil",
    "localizacao": "Valinhos, SP, Brasil",
    "descricao": "Usuário da cidade de Valinhos.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.9841935,-46.9805303",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 22,
    "nome": "Rafael Oliveira",
    "cidade": "Campinas",
    "estado": "SP",
    "latitude": -22.9099,
    "longitude": -47.0626,
    "cep": "13064862",
    "pais": "Brasil",
    "localizacao": "Campinas, SP, Brasil",
    "descricao": "Usuário da cidade de Campinas.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.9099,-47.0626",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 23,
    "nome": "andreluizbedin@yahoo.com.br",
    "cidade": "Jaguariúna",
    "estado": "SP",
    "latitude": -22.6996652,
    "longitude": -46.9929159,
    "cep": "13911062",
    "pais": "Brasil",
    "localizacao": "Jaguariúna, SP, Brasil",
    "descricao": "Usuário da cidade de Jaguariúna.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.6996652,-46.9929159",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 24,
    "nome": "Fabiano Soares",
    "cidade": "Campinas",
    "estado": "SP",
    "latitude": -22.8639094,
    "longitude": -47.1440188,
    "cep": "13067356",
    "pais": "Brasil",
    "localizacao": "Campinas, SP, Brasil",
    "descricao": "Usuário da cidade de Campinas.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.8639094,-47.1440188",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 25,
    "nome": "PETERSON RISSO",
    "cidade": "Americana",
    "estado": "SP",
    "latitude": -22.7283727,
    "longitude": -47.3004621,
    "cep": "13473040",
    "pais": "Brasil",
    "localizacao": "Americana, SP, Brasil",
    "descricao": "Usuário da cidade de Americana.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.7283727,-47.3004621",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 26,
    "nome": "Renato Masson",
    "cidade": "Sumaré",
    "estado": "SP",
    "latitude": -22.8238635,
    "longitude": -47.28698,
    "cep": "13172794",
    "pais": "Brasil",
    "localizacao": "Sumaré, SP, Brasil",
    "descricao": "Usuário da cidade de Sumaré.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.8238635,-47.28698",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 27,
    "nome": "Joao Carlos Simoes Junior",
    "cidade": "Campinas",
    "estado": "SP",
    "latitude": -22.9109054,
    "longitude": -47.0521818,
    "cep": "13026001",
    "pais": "Brasil",
    "localizacao": "Campinas, SP, Brasil",
    "descricao": "Usuário da cidade de Campinas.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.9109054,-47.0521818",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 28,
    "nome": "Richard Silva Vilas Boas",
    "cidade": "Campinas",
    "estado": "SP",
    "latitude": -22.9892034,
    "longitude": -47.1153765,
    "cep": "13054353",
    "pais": "Brasil",
    "localizacao": "Campinas, SP, Brasil",
    "descricao": "Usuário da cidade de Campinas.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.9892034,-47.1153765",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 29,
    "nome": "William Paixão",
    "cidade": "Campinas",
    "estado": "SP",
    "latitude": -22.9471187,
    "longitude": -47.032606,
    "cep": "13045135",
    "pais": "Brasil",
    "localizacao": "Campinas, SP, Brasil",
    "descricao": "Usuário da cidade de Campinas.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.9471187,-47.032606",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 30,
    "nome": "Fábio Rogério Gudaitis Gonçalves",
    "cidade": "Indaiatuba",
    "estado": "SP",
    "latitude": -23.1231882,
    "longitude": -47.230564,
    "cep": "13346480",
    "pais": "Brasil",
    "localizacao": "Indaiatuba, SP, Brasil",
    "descricao": "Usuário da cidade de Indaiatuba.",
    "link": "https://www.google.com/maps/search/?api=1&query=-23.1231882,-47.230564",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 31,
    "nome": "allan fernandes ribeiro",
    "cidade": "Campinas",
    "estado": "SP",
    "latitude": -22.9278024,
    "longitude": -47.116801,
    "cep": "13060571",
    "pais": "Brasil",
    "localizacao": "Campinas, SP, Brasil",
    "descricao": "Usuário da cidade de Campinas.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.9278024,-47.116801",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 32,
    "nome": "Cássia Queiroz",
    "cidade": "Hortolândia",
    "estado": "SP",
    "latitude": -22.8601,
    "longitude": -47.2127,
    "cep": "13185844",
    "pais": "Brasil",
    "localizacao": "Hortolândia, SP, Brasil",
    "descricao": "Usuário da cidade de Hortolândia.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.8601,-47.2127",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 33,
    "nome": "Alex Maciel Rodrigues",
    "cidade": "Jundiaí",
    "estado": "SP",
    "latitude": -23.2452332,
    "longitude": -46.8565464,
    "cep": "13205732",
    "pais": "Brasil",
    "localizacao": "Jundiaí, SP, Brasil",
    "descricao": "Usuário da cidade de Jundiaí.",
    "link": "https://www.google.com/maps/search/?api=1&query=-23.2452332,-46.8565464",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 34,
    "nome": "robson de araujo paula",
    "cidade": "Sumaré",
    "estado": "SP",
    "latitude": -22.8227,
    "longitude": -47.1047,
    "cep": "13173433",
    "pais": "Brasil",
    "localizacao": "Sumaré, SP, Brasil",
    "descricao": "Usuário da cidade de Sumaré.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.8227,-47.1047",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 35,
    "nome": "Leonardo Souza Lôbo",
    "cidade": "Campinas",
    "estado": "SP",
    "latitude": -22.9464264,
    "longitude": -47.0265448,
    "cep": "13045165",
    "pais": "Brasil",
    "localizacao": "Campinas, SP, Brasil",
    "descricao": "Usuário da cidade de Campinas.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.9464264,-47.0265448",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 36,
    "nome": "Camila Candreva",
    "cidade": "Campinas",
    "estado": "SP",
    "latitude": -22.9615427,
    "longitude": -47.0508372,
    "cep": "13042710",
    "pais": "Brasil",
    "localizacao": "Campinas, SP, Brasil",
    "descricao": "Usuário da cidade de Campinas.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.9615427,-47.0508372",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 37,
    "nome": "Leandro Renato Trombini",
    "cidade": "Hortolândia",
    "estado": "SP",
    "latitude": -22.9021291,
    "longitude": -47.1954572,
    "cep": "13186521",
    "pais": "Brasil",
    "localizacao": "Hortolândia, SP, Brasil",
    "descricao": "Usuário da cidade de Hortolândia.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.9021291,-47.1954572",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 38,
    "nome": "Genivaldo Ferreira",
    "cidade": "Americana",
    "estado": "SP",
    "latitude": -22.7205895,
    "longitude": -47.3494206,
    "cep": "13470220",
    "pais": "Brasil",
    "localizacao": "Americana, SP, Brasil",
    "descricao": "Usuário da cidade de Americana.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.7205895,-47.3494206",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 39,
    "nome": "EMERSON",
    "cidade": "Hortolândia",
    "estado": "SP",
    "latitude": -22.8839734,
    "longitude": -47.2022231,
    "cep": "13186170",
    "pais": "Brasil",
    "localizacao": "Hortolândia, SP, Brasil",
    "descricao": "Usuário da cidade de Hortolândia.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.8839734,-47.2022231",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 40,
    "nome": "Rodrigo Murari",
    "cidade": "Campinas",
    "estado": "SP",
    "latitude": -22.9254342,
    "longitude": -47.1168349,
    "cep": "13060367",
    "pais": "Brasil",
    "localizacao": "Campinas, SP, Brasil",
    "descricao": "Usuário da cidade de Campinas.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.9254342,-47.1168349",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 41,
    "nome": "Felipe Bisco",
    "cidade": "Campinas",
    "estado": "SP",
    "latitude": -22.8909327,
    "longitude": -46.9803095,
    "cep": "13105672",
    "pais": "Brasil",
    "localizacao": "Campinas, SP, Brasil",
    "descricao": "Usuário da cidade de Campinas.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.8909327,-46.9803095",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 42,
    "nome": "Wellington Lima",
    "cidade": "Hortolândia",
    "estado": "SP",
    "latitude": -22.8794004,
    "longitude": -47.2045346,
    "cep": "13186013",
    "pais": "Brasil",
    "localizacao": "Hortolândia, SP, Brasil",
    "descricao": "Usuário da cidade de Hortolândia.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.8794004,-47.2045346",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 43,
    "nome": "Marcel Murayama",
    "cidade": "Campinas",
    "estado": "SP",
    "latitude": -22.9339272,
    "longitude": -47.0590281,
    "cep": "13040089",
    "pais": "Brasil",
    "localizacao": "Campinas, SP, Brasil",
    "descricao": "Usuário da cidade de Campinas.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.9339272,-47.0590281",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 44,
    "nome": "jullia Magno",
    "cidade": "Campinas",
    "estado": "SP",
    "latitude": -22.9526727,
    "longitude": -47.1634092,
    "cep": "13059194",
    "pais": "Brasil",
    "localizacao": "Campinas, SP, Brasil",
    "descricao": "Usuário da cidade de Campinas.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.9526727,-47.1634092",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 45,
    "nome": "Fábio Camargo",
    "cidade": "Campinas",
    "estado": "SP",
    "latitude": -22.9254688,
    "longitude": -47.0733412,
    "cep": "13030540",
    "pais": "Brasil",
    "localizacao": "Campinas, SP, Brasil",
    "descricao": "Usuário da cidade de Campinas.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.9254688,-47.0733412",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 46,
    "nome": "nilson da silva barbosa",
    "cidade": "Limeira",
    "estado": "SP",
    "latitude": -22.6147446,
    "longitude": -47.422346,
    "cep": "13481274",
    "pais": "Brasil",
    "localizacao": "Limeira, SP, Brasil",
    "descricao": "Usuário da cidade de Limeira.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.6147446,-47.422346",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 47,
    "nome": "Ricardo Alexandre Pereira",
    "cidade": "Campinas",
    "estado": "SP",
    "latitude": -22.9778664,
    "longitude": -47.1435873,
    "cep": "13056400",
    "pais": "Brasil",
    "localizacao": "Campinas, SP, Brasil",
    "descricao": "Usuário da cidade de Campinas.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.9778664,-47.1435873",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 48,
    "nome": "Roberta Aparecida de Brito Benez",
    "cidade": "Campinas",
    "estado": "SP",
    "latitude": -22.8980637,
    "longitude": -47.0675449,
    "cep": "13020110",
    "pais": "Brasil",
    "localizacao": "Campinas, SP, Brasil",
    "descricao": "Usuário da cidade de Campinas.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.8980637,-47.0675449",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 49,
    "nome": "Adenilson Luiz Pedro",
    "cidade": "Santa Bárbara D’Oeste",
    "estado": "SP",
    "latitude": -22.757,
    "longitude": -47.4087,
    "cep": "13451190",
    "pais": "Brasil",
    "localizacao": "Santa Bárbara D’Oeste, SP, Brasil",
    "descricao": "Usuário da cidade de Santa Bárbara D’Oeste.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.757,-47.4087",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 50,
    "nome": "Silvino V. Vieira",
    "cidade": "Limeira",
    "estado": "SP",
    "latitude": -22.5540246,
    "longitude": -47.4524335,
    "cep": "13483506",
    "pais": "Brasil",
    "localizacao": "Limeira, SP, Brasil",
    "descricao": "Usuário da cidade de Limeira.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.5540246,-47.4524335",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 51,
    "nome": "Lucas José de Souza Silva",
    "cidade": "Valinhos",
    "estado": "SP",
    "latitude": -22.9761443,
    "longitude": -46.9884262,
    "cep": "13275410",
    "pais": "Brasil",
    "localizacao": "Valinhos, SP, Brasil",
    "descricao": "Usuário da cidade de Valinhos.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.9761443,-46.9884262",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 52,
    "nome": "Elton sa da silva",
    "cidade": "Hortolândia",
    "estado": "SP",
    "latitude": -22.9031228,
    "longitude": -47.2468119,
    "cep": "13188191",
    "pais": "Brasil",
    "localizacao": "Hortolândia, SP, Brasil",
    "descricao": "Usuário da cidade de Hortolândia.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.9031228,-47.2468119",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 53,
    "nome": "Gionedes Aparecido Martins Seabra",
    "cidade": "Hortolândia",
    "estado": "SP",
    "latitude": -22.8839734,
    "longitude": -47.2022231,
    "cep": "13186020",
    "pais": "Brasil",
    "localizacao": "Hortolândia, SP, Brasil",
    "descricao": "Usuário da cidade de Hortolândia.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.8839734,-47.2022231",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 54,
    "nome": "Anderson Santos",
    "cidade": "Sumaré",
    "estado": "SP",
    "latitude": -22.8136892,
    "longitude": -47.2296625,
    "cep": "13177292",
    "pais": "Brasil",
    "localizacao": "Sumaré, SP, Brasil",
    "descricao": "Usuário da cidade de Sumaré.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.8136892,-47.2296625",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 55,
    "nome": "Abayomiakili André Macedo",
    "cidade": "Campinas",
    "estado": "SP",
    "latitude": -22.9641762,
    "longitude": -47.1703876,
    "cep": "13057201",
    "pais": "Brasil",
    "localizacao": "Campinas, SP, Brasil",
    "descricao": "Usuário da cidade de Campinas.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.9641762,-47.1703876",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 56,
    "nome": "Erika Aparecida Gilioli",
    "cidade": "Campinas",
    "estado": "SP",
    "latitude": -22.9466673,
    "longitude": -47.1207725,
    "cep": "13060773",
    "pais": "Brasil",
    "localizacao": "Campinas, SP, Brasil",
    "descricao": "Usuário da cidade de Campinas.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.9466673,-47.1207725",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 57,
    "nome": "Gilvania Sousa Silva",
    "cidade": "Valinhos",
    "estado": "SP",
    "latitude": -22.9392976,
    "longitude": -46.9721956,
    "cep": "13273220",
    "pais": "Brasil",
    "localizacao": "Valinhos, SP, Brasil",
    "descricao": "Usuário da cidade de Valinhos.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.9392976,-46.9721956",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 58,
    "nome": "Marcelo Felipe dos Santos",
    "cidade": "Hortolândia",
    "estado": "SP",
    "latitude": -22.8790882,
    "longitude": -47.1961951,
    "cep": "13186330",
    "pais": "Brasil",
    "localizacao": "Hortolândia, SP, Brasil",
    "descricao": "Usuário da cidade de Hortolândia.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.8790882,-47.1961951",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 59,
    "nome": "Luciano Beteto",
    "cidade": "Pedreira",
    "estado": "SP",
    "latitude": -22.741347,
    "longitude": -46.894846,
    "cep": "13920000",
    "pais": "Brasil",
    "localizacao": "Pedreira, SP, Brasil",
    "descricao": "Usuário da cidade de Pedreira.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.741347,-46.894846",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 60,
    "nome": "Michele Gomes de Jesus",
    "cidade": "Campinas",
    "estado": "SP",
    "latitude": -22.9541865,
    "longitude": -47.0769735,
    "cep": "13051410",
    "pais": "Brasil",
    "localizacao": "Campinas, SP, Brasil",
    "descricao": "Usuário da cidade de Campinas.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.9541865,-47.0769735",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 61,
    "nome": "Adriana Paula de Sousa Alvarenga",
    "cidade": "Campinas",
    "estado": "SP",
    "latitude": -22.9293324,
    "longitude": -47.0572737,
    "cep": "13040735",
    "pais": "Brasil",
    "localizacao": "Campinas, SP, Brasil",
    "descricao": "Usuário da cidade de Campinas.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.9293324,-47.0572737",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 62,
    "nome": "JALMIR VIEIRA DOS SANTOS",
    "cidade": "Campinas",
    "estado": "SP",
    "latitude": -22.976843,
    "longitude": -47.1164158,
    "cep": "13054541",
    "pais": "Brasil",
    "localizacao": "Campinas, SP, Brasil",
    "descricao": "Usuário da cidade de Campinas.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.976843,-47.1164158",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 63,
    "nome": "David Fabio da Silva",
    "cidade": "Campinas",
    "estado": "SP",
    "latitude": -22.9380711,
    "longitude": -47.116636,
    "cep": "13060740",
    "pais": "Brasil",
    "localizacao": "Campinas, SP, Brasil",
    "descricao": "Usuário da cidade de Campinas.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.9380711,-47.116636",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 64,
    "nome": "Raphael Montali da Assumpção",
    "cidade": "Campinas",
    "estado": "SP",
    "latitude": -22.8779459,
    "longitude": -47.0510204,
    "cep": "13076869",
    "pais": "Brasil",
    "localizacao": "Campinas, SP, Brasil",
    "descricao": "Usuário da cidade de Campinas.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.8779459,-47.0510204",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 65,
    "nome": "Daniel Guimarães Sanches",
    "cidade": "Valinhos",
    "estado": "SP",
    "latitude": -22.9973292,
    "longitude": -47.0180416,
    "cep": "13278210",
    "pais": "Brasil",
    "localizacao": "Valinhos, SP, Brasil",
    "descricao": "Usuário da cidade de Valinhos.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.9973292,-47.0180416",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 66,
    "nome": "Fábio Almeida Silva",
    "cidade": "Vinhedo",
    "estado": "SP",
    "latitude": -23.0289,
    "longitude": -46.9744,
    "cep": "13284488",
    "pais": "Brasil",
    "localizacao": "Vinhedo, SP, Brasil",
    "descricao": "Usuário da cidade de Vinhedo.",
    "link": "https://www.google.com/maps/search/?api=1&query=-23.0289,-46.9744",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 67,
    "nome": "Marcelo Alves Bandeira",
    "cidade": "Americana",
    "estado": "SP",
    "latitude": -22.7304316,
    "longitude": -47.284983,
    "cep": "13475010",
    "pais": "Brasil",
    "localizacao": "Americana, SP, Brasil",
    "descricao": "Usuário da cidade de Americana.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.7304316,-47.284983",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 68,
    "nome": "ƎꓶⱯ",
    "cidade": "Campinas",
    "estado": "SP",
    "latitude": -22.9000726,
    "longitude": -47.0970989,
    "cep": "13033740",
    "pais": "Brasil",
    "localizacao": "Campinas, SP, Brasil",
    "descricao": "Usuário da cidade de Campinas.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.9000726,-47.0970989",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 69,
    "nome": "Roberta Monteiro",
    "cidade": "Valinhos",
    "estado": "SP",
    "latitude": -22.9060283,
    "longitude": -46.976542,
    "cep": "13273300",
    "pais": "Brasil",
    "localizacao": "Valinhos, SP, Brasil",
    "descricao": "Usuário da cidade de Valinhos.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.9060283,-46.976542",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 70,
    "nome": "Henrique Seiji Higashie Ike",
    "cidade": "Campinas",
    "estado": "SP",
    "latitude": -22.8732349,
    "longitude": -47.0284539,
    "cep": "13091012",
    "pais": "Brasil",
    "localizacao": "Campinas, SP, Brasil",
    "descricao": "Usuário da cidade de Campinas.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.8732349,-47.0284539",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 71,
    "nome": "Murilo Pereira Oliveira",
    "cidade": "Campinas",
    "estado": "SP",
    "latitude": -22.9075221,
    "longitude": -47.0556501,
    "cep": "13015122",
    "pais": "Brasil",
    "localizacao": "Campinas, SP, Brasil",
    "descricao": "Usuário da cidade de Campinas.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.9075221,-47.0556501",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 72,
    "nome": "Thiago Silveira",
    "cidade": "Campinas",
    "estado": "SP",
    "latitude": -22.9123495,
    "longitude": -47.0542174,
    "cep": "13026064",
    "pais": "Brasil",
    "localizacao": "Campinas, SP, Brasil",
    "descricao": "Usuário da cidade de Campinas.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.9123495,-47.0542174",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 73,
    "nome": "Daniel Marcos Marichi",
    "cidade": "Campinas",
    "estado": "SP",
    "latitude": -22.9065228,
    "longitude": -47.1172128,
    "cep": "13061100",
    "pais": "Brasil",
    "localizacao": "Campinas, SP, Brasil",
    "descricao": "Usuário da cidade de Campinas.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.9065228,-47.1172128",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 74,
    "nome": "SOLANGE COUTINHO DOS SANTOS",
    "cidade": "Campinas",
    "estado": "SP",
    "latitude": -22.952742,
    "longitude": -47.1828226,
    "cep": "13058358",
    "pais": "Brasil",
    "localizacao": "Campinas, SP, Brasil",
    "descricao": "Usuário da cidade de Campinas.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.952742,-47.1828226",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 75,
    "nome": "dennis frank rezende",
    "cidade": "Campinas",
    "estado": "SP",
    "latitude": -22.9565814,
    "longitude": -47.1928846,
    "cep": "13058017",
    "pais": "Brasil",
    "localizacao": "Campinas, SP, Brasil",
    "descricao": "Usuário da cidade de Campinas.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.9565814,-47.1928846",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 76,
    "nome": "Ruy Guilherme Vieira da Silva evangelista",
    "cidade": "Valinhos",
    "estado": "SP",
    "latitude": -22.9392976,
    "longitude": -46.9721956,
    "cep": "13273220",
    "pais": "Brasil",
    "localizacao": "Valinhos, SP, Brasil",
    "descricao": "Usuário da cidade de Valinhos.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.9392976,-46.9721956",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 77,
    "nome": "Marcelo Freitas",
    "cidade": "Sumaré",
    "estado": "SP",
    "latitude": -22.8227,
    "longitude": -47.1047,
    "cep": "13173482",
    "pais": "Brasil",
    "localizacao": "Sumaré, SP, Brasil",
    "descricao": "Usuário da cidade de Sumaré.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.8227,-47.1047",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 78,
    "nome": "Douglas henrique borges",
    "cidade": "Campinas",
    "estado": "SP",
    "latitude": -22.8708673,
    "longitude": -47.062513,
    "cep": "13087320",
    "pais": "Brasil",
    "localizacao": "Campinas, SP, Brasil",
    "descricao": "Usuário da cidade de Campinas.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.8708673,-47.062513",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 79,
    "nome": "Clecio De Souza Carvalho",
    "cidade": "Sumaré",
    "estado": "SP",
    "latitude": -22.8160143,
    "longitude": -47.1638459,
    "cep": "13179322",
    "pais": "Brasil",
    "localizacao": "Sumaré, SP, Brasil",
    "descricao": "Usuário da cidade de Sumaré.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.8160143,-47.1638459",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 80,
    "nome": "Edmir da chaga silveira",
    "cidade": "Campinas",
    "estado": "SP",
    "latitude": -22.9460931,
    "longitude": -47.1234351,
    "cep": "13060766",
    "pais": "Brasil",
    "localizacao": "Campinas, SP, Brasil",
    "descricao": "Usuário da cidade de Campinas.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.9460931,-47.1234351",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 81,
    "nome": "Antonio aparecido dias Fernandes",
    "cidade": "Sumaré",
    "estado": "SP",
    "latitude": -22.79312,
    "longitude": -47.1977505,
    "cep": "13178353",
    "pais": "Brasil",
    "localizacao": "Sumaré, SP, Brasil",
    "descricao": "Usuário da cidade de Sumaré.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.79312,-47.1977505",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 82,
    "nome": "Alexandre Fernando Zazia",
    "cidade": "Campinas",
    "estado": "SP",
    "latitude": -22.91746,
    "longitude": -47.1017742,
    "cep": "13060073",
    "pais": "Brasil",
    "localizacao": "Campinas, SP, Brasil",
    "descricao": "Usuário da cidade de Campinas.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.91746,-47.1017742",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 83,
    "nome": "lorenlayr13@gmail.com",
    "cidade": "Campinas",
    "estado": "SP",
    "latitude": -22.9214184,
    "longitude": -47.0418145,
    "cep": "13100430",
    "pais": "Brasil",
    "localizacao": "Campinas, SP, Brasil",
    "descricao": "Usuário da cidade de Campinas.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.9214184,-47.0418145",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 84,
    "nome": "MARCOS WILLIAM Gonçalves Miranda VIEIRA",
    "cidade": "Sumaré",
    "estado": "SP",
    "latitude": -22.8086625,
    "longitude": -47.2040194,
    "cep": "13178321",
    "pais": "Brasil",
    "localizacao": "Sumaré, SP, Brasil",
    "descricao": "Usuário da cidade de Sumaré.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.8086625,-47.2040194",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 85,
    "nome": "Wellington rodrigo de oliveira",
    "cidade": "Campinas",
    "estado": "SP",
    "latitude": -22.9736336,
    "longitude": -47.1711701,
    "cep": "13057400",
    "pais": "Brasil",
    "localizacao": "Campinas, SP, Brasil",
    "descricao": "Usuário da cidade de Campinas.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.9736336,-47.1711701",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 86,
    "nome": "Kristiane Aparecida Daenekas",
    "cidade": "Valinhos",
    "estado": "SP",
    "latitude": -22.940511,
    "longitude": -47.0008297,
    "cep": "13272700",
    "pais": "Brasil",
    "localizacao": "Valinhos, SP, Brasil",
    "descricao": "Usuário da cidade de Valinhos.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.940511,-47.0008297",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 87,
    "nome": "Igor dos Santos",
    "cidade": "Valinhos",
    "estado": "SP",
    "latitude": -22.9772,
    "longitude": -46.989,
    "cep": "13274560",
    "pais": "Brasil",
    "localizacao": "Valinhos, SP, Brasil",
    "descricao": "Usuário da cidade de Valinhos.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.9772,-46.989",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 88,
    "nome": "wilson silva",
    "cidade": "Campinas",
    "estado": "SP",
    "latitude": -22.9750222,
    "longitude": -47.1451955,
    "cep": "13056425",
    "pais": "Brasil",
    "localizacao": "Campinas, SP, Brasil",
    "descricao": "Usuário da cidade de Campinas.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.9750222,-47.1451955",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 89,
    "nome": "AL",
    "cidade": "Valinhos",
    "estado": "SP",
    "latitude": -22.9396666,
    "longitude": -46.9738752,
    "cep": "13273649",
    "pais": "Brasil",
    "localizacao": "Valinhos, SP, Brasil",
    "descricao": "Usuário da cidade de Valinhos.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.9396666,-46.9738752",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 90,
    "nome": "Thais Lobo",
    "cidade": "Campinas",
    "estado": "SP",
    "latitude": -22.9594918,
    "longitude": -47.1842196,
    "cep": "13058381",
    "pais": "Brasil",
    "localizacao": "Campinas, SP, Brasil",
    "descricao": "Usuário da cidade de Campinas.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.9594918,-47.1842196",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 91,
    "nome": "Marcelo Roberto",
    "cidade": "Valinhos",
    "estado": "SP",
    "latitude": -22.9505183,
    "longitude": -46.9725696,
    "cep": "13273601",
    "pais": "Brasil",
    "localizacao": "Valinhos, SP, Brasil",
    "descricao": "Usuário da cidade de Valinhos.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.9505183,-46.9725696",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 92,
    "nome": "leandro lopes da silva",
    "cidade": "Campinas",
    "estado": "SP",
    "latitude": -22.9202183,
    "longitude": -47.102124,
    "cep": "13060061",
    "pais": "Brasil",
    "localizacao": "Campinas, SP, Brasil",
    "descricao": "Usuário da cidade de Campinas.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.9202183,-47.102124",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 93,
    "nome": "Erika Rondina",
    "cidade": "Hortolândia",
    "estado": "SP",
    "latitude": -22.9062771,
    "longitude": -47.1749254,
    "cep": "13185340",
    "pais": "Brasil",
    "localizacao": "Hortolândia, SP, Brasil",
    "descricao": "Usuário da cidade de Hortolândia.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.9062771,-47.1749254",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 94,
    "nome": "Renato Novaes",
    "cidade": "Americana",
    "estado": "SP",
    "latitude": -22.7007656,
    "longitude": -47.2949187,
    "cep": "13474580",
    "pais": "Brasil",
    "localizacao": "Americana, SP, Brasil",
    "descricao": "Usuário da cidade de Americana.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.7007656,-47.2949187",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 95,
    "nome": "Antonio Vieira",
    "cidade": "Hortolândia",
    "estado": "SP",
    "latitude": -22.8601,
    "longitude": -47.2127,
    "cep": "13181580",
    "pais": "Brasil",
    "localizacao": "Hortolândia, SP, Brasil",
    "descricao": "Usuário da cidade de Hortolândia.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.8601,-47.2127",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 96,
    "nome": "William Viana Mapelli",
    "cidade": "Valinhos",
    "estado": "SP",
    "latitude": -22.9520271,
    "longitude": -46.9718894,
    "cep": "13273608",
    "pais": "Brasil",
    "localizacao": "Valinhos, SP, Brasil",
    "descricao": "Usuário da cidade de Valinhos.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.9520271,-46.9718894",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 97,
    "nome": "Diego Lobo",
    "cidade": "Campinas",
    "estado": "SP",
    "latitude": -22.9509438,
    "longitude": -47.1772102,
    "cep": "13058301",
    "pais": "Brasil",
    "localizacao": "Campinas, SP, Brasil",
    "descricao": "Usuário da cidade de Campinas.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.9509438,-47.1772102",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 98,
    "nome": "Anderson Canciano",
    "cidade": "Campinas",
    "estado": "SP",
    "latitude": -22.9664154,
    "longitude": -47.1691105,
    "cep": "13057189",
    "pais": "Brasil",
    "localizacao": "Campinas, SP, Brasil",
    "descricao": "Usuário da cidade de Campinas.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.9664154,-47.1691105",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 99,
    "nome": "Jean Rodrigues da Luz",
    "cidade": "Campinas",
    "estado": "SP",
    "latitude": -22.8763501,
    "longitude": -47.0451729,
    "cep": "13076001",
    "pais": "Brasil",
    "localizacao": "Campinas, SP, Brasil",
    "descricao": "Usuário da cidade de Campinas.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.8763501,-47.0451729",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 100,
    "nome": "Helena Ribeiro",
    "cidade": "Campinas",
    "estado": "SP",
    "latitude": -22.9099,
    "longitude": -47.0626,
    "cep": "13057036",
    "pais": "Brasil",
    "localizacao": "Campinas, SP, Brasil",
    "descricao": "Usuário da cidade de Campinas.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.9099,-47.0626",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
];
