// dados.js
const locations = [
    
  {
    "id": 1,
    "nome": "Juliane Ap. Cyrilo Cunha",
    "cidade": "Paulínia",
    "estado": "SP",
    "latitude": -22.744338,
    "longitude": -47.1767203,
    "cep": "13145352",
    "pais": "Brasil",
    "localizacao": "Paulínia, SP, Brasil",
    "descricao": "Usuário da cidade de Paulínia.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.744338,-47.1767203",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 2,
    "nome": "João Paulo de Moraes",
    "cidade": "Campinas",
    "estado": "SP",
    "latitude": -22.9320985,
    "longitude": -47.0762548,
    "cep": "13050008",
    "pais": "Brasil",
    "localizacao": "Campinas, SP, Brasil",
    "descricao": "Usuário da cidade de Campinas.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.9320985,-47.0762548",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 3,
    "nome": "Lucas Cunha",
    "cidade": "Campinas",
    "estado": "SP",
    "latitude": -22.8533533,
    "longitude": -47.0469649,
    "cep": "13087500",
    "pais": "Brasil",
    "localizacao": "Campinas, SP, Brasil",
    "descricao": "Usuário da cidade de Campinas.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.8533533,-47.0469649",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 4,
    "nome": "Aline Tortosa",
    "cidade": "Campinas",
    "estado": "SP",
    "latitude": -22.9421519,
    "longitude": -47.0230088,
    "cep": "13045260",
    "pais": "Brasil",
    "localizacao": "Campinas, SP, Brasil",
    "descricao": "Usuário da cidade de Campinas.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.9421519,-47.0230088",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 5,
    "nome": "Alexx Amatuzzi",
    "cidade": "Valinhos",
    "estado": "SP",
    "latitude": -22.9772,
    "longitude": -46.989,
    "cep": "13322020",
    "pais": "Brasil",
    "localizacao": "Valinhos, SP, Brasil",
    "descricao": "Usuário da cidade de Valinhos.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.9772,-46.989",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 6,
    "nome": "Ricardo Augusto Costa Raven",
    "cidade": "Hortolândia",
    "estado": "SP",
    "latitude": -22.8862883,
    "longitude": -47.2013605,
    "cep": "13186635",
    "pais": "Brasil",
    "localizacao": "Hortolândia, SP, Brasil",
    "descricao": "Usuário da cidade de Hortolândia.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.8862883,-47.2013605",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 7,
    "nome": "Carlos Eduardo Pereira de Souza",
    "cidade": "Campinas",
    "estado": "SP",
    "latitude": -22.9826214,
    "longitude": -47.1202832,
    "cep": "13054421",
    "pais": "Brasil",
    "localizacao": "Campinas, SP, Brasil",
    "descricao": "Usuário da cidade de Campinas.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.9826214,-47.1202832",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 8,
    "nome": "Adrian Roberto Chiminazzo",
    "cidade": "Valinhos",
    "estado": "SP",
    "latitude": -22.9813643,
    "longitude": -46.9938373,
    "cep": "13276409",
    "pais": "Brasil",
    "localizacao": "Valinhos, SP, Brasil",
    "descricao": "Usuário da cidade de Valinhos.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.9813643,-46.9938373",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 9,
    "nome": "Roberta Dos Santos Silva",
    "cidade": "Campinas",
    "estado": "SP",
    "latitude": -22.9710829,
    "longitude": -47.1572759,
    "cep": "13056204",
    "pais": "Brasil",
    "localizacao": "Campinas, SP, Brasil",
    "descricao": "Usuário da cidade de Campinas.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.9710829,-47.1572759",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
  },
  {
    "id": 10,
    "nome": "Ingryd Micheli Breg",
    "cidade": "Limeira",
    "estado": "SP",
    "latitude": -22.5571965,
    "longitude": -47.3772316,
    "cep": "13486333",
    "pais": "Brasil",
    "localizacao": "Limeira, SP, Brasil",
    "descricao": "Usuário da cidade de Limeira.",
    "link": "https://www.google.com/maps/search/?api=1&query=-22.5571965,-47.3772316",
    "icone": "https://maps.google.com/mapfiles/ms/icons/red-dot.png"
   }
];
